spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mail}}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
resend:
  api:
    key: ${RESEND_API_KEY}
  from:
    email: ${RESEND_FROM_EMAIL:onboarding@resend.dev}